# TIP: los comando que menos se modifica mejor que esten arriba

# imagen base, trabajamos con imagenes ya creadas
# este es nuestro punto inicial sobre el que trabaja nuestra app
FROM node:19.2-alpine3.16
# esta imagen internamente tiene una carpeta app

# cambiamos de directorio a app
WORKDIR /app

COPY  package.json ./

# instalamos dependencias de la app
RUN npm install

#copiamos todo, mal!
COPY . .

# realizar test
RUN npm run test


# comando a ejecutar cuando se levante el container
CMD ["node", "app.js"]