version: '3'

# Aqui declaramos todas las tareas
services:
  # contenedor para la base de datos
  # db es el nombre del servicio
  db:
    container_name: "postgres-db-container"
    image: postgres:15.1
    volumes:
      - postgres-db-volu:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
  # contenedor para el pgadmin
  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=superman@google.com